"""Build top_frequency_candidates.json from compact in-script tuples.

Each candidate is (hebrew_with_nikud, transcription, english_gloss, ukrainian_gloss).
Categories are grouped below; the script attaches the category key on emit.
"""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "docs" / "vocabulary_expansion" / "top_frequency_candidates.json"

FUNCTION_WORDS = [
    ("אֲבָל", "aval", "but", "але"),
    ("אוֹ", "o", "or", "або"),
    ("כִּי", "ki", "because; that", "бо; що"),
    ("אִם", "im", "if", "якщо"),
    ("שֶׁ", "she", "that (subordinator)", "що"),
    ("גַּם", "gam", "also; too", "теж; також"),
    ("רַק", "rak", "only", "лише"),
    ("עוֹד", "od", "still; more", "ще"),
    ("כְּבָר", "kvar", "already", "вже"),
    ("אוּלָם", "ulam", "however", "проте"),
    ("בְּכָל זֹאת", "bekhol zot", "nevertheless", "усе ж"),
    ("לָכֵן", "lakhen", "therefore", "тому"),
    ("בִּגְלַל", "biglal", "because of", "через"),
    ("מִפְּנֵי שֶׁ", "mipnei she", "because", "через те що"),
    ("כֵּיוָן שֶׁ", "keivan she", "since", "оскільки"),
    ("בִּזְמַן שֶׁ", "bizman she", "while", "поки"),
    ("כְּשֶׁ", "kshe", "when (conj.)", "коли"),
    ("לִפְנֵי שֶׁ", "lifnei she", "before (conj.)", "до того як"),
    ("אַחֲרֵי שֶׁ", "acharei she", "after (conj.)", "після того як"),
    ("בְּעוֹד שֶׁ", "be'od she", "whereas; while", "тоді як"),
    ("כְּדֵי", "kedei", "in order to", "щоб"),
    ("כְּדֵי שֶׁ", "kedei she", "so that", "щоб"),
    ("בִּשְׁבִיל", "bishvil", "for; for the sake of", "для"),
    ("בְּעֶצֶם", "be'etzem", "actually", "насправді"),
    ("בֶּאֱמֶת", "be'emet", "really", "справді"),
    ("בְּדִיּוּק", "bediyuk", "exactly", "саме; точно"),
    ("בְּעִקָּר", "be'ikar", "mainly", "переважно"),
    ("בִּמְיֻחָד", "bimyukhad", "especially", "особливо"),
    ("בְּדֶרֶךְ כְּלָל", "bederekh klal", "usually", "зазвичай"),
    ("בְּכָל אֹפֶן", "bekhol ofen", "anyway", "у всякому разі"),
    ("בְּכָל מִקְרֶה", "bekhol mikre", "in any case", "у будь-якому разі"),
    ("אַף עַל פִּי כֵן", "af al pi khen", "nevertheless", "однак"),
    ("כְּלוֹמַר", "klomar", "that is; meaning", "тобто"),
    ("לְמָשָׁל", "lemashal", "for example", "наприклад"),
    ("כְּמוֹ", "kemo", "like; as", "як"),
    ("כְּמוֹ כֵן", "kemo khen", "likewise", "так само"),
    ("חוּץ מִ", "chutz mi", "except for", "крім"),
    ("מִלְּבַד", "milvad", "except", "окрім"),
    ("בִּמְקוֹם", "bimkom", "instead of", "замість"),
    ("לְעֻמַּת", "le'umat", "compared to", "порівняно з"),
    ("נֶגֶד", "neged", "against", "проти"),
    ("בְּעַד", "be'ad", "in favor of", "за"),
    ("לְפִי", "lefi", "according to", "згідно з"),
    ("עַל פִּי", "al pi", "according to", "згідно"),
    ("מִתּוֹךְ", "mitokh", "out of; from within", "із; з"),
    ("בְּאֶמְצָעוּת", "be'emtsa'ut", "by means of", "за допомогою"),
    ("עַל יְדֵי", "al yedei", "by; through", "через"),
    ("אַף", "af", "even", "навіть"),
    ("הֲרֵי", "harei", "indeed; after all", "адже"),
    ("דַּוְקָא", "davka", "specifically; just", "якраз"),
    ("אֲפִילּוּ", "afilu", "even", "навіть"),
]

PRONOUNS = [
    ("אֲנִי", "ani", "I", "я"),
    ("אַתָּה", "ata", "you (m.sg)", "ти (ч.)"),
    ("אַתְּ", "at", "you (f.sg)", "ти (ж.)"),
    ("הוּא", "hu", "he", "він"),
    ("הִיא", "hi", "she", "вона"),
    ("אֲנַחְנוּ", "anachnu", "we", "ми"),
    ("אַתֶּם", "atem", "you (m.pl)", "ви (ч.)"),
    ("אַתֶּן", "aten", "you (f.pl)", "ви (ж.)"),
    ("הֵם", "hem", "they (m)", "вони (ч.)"),
    ("הֵן", "hen", "they (f)", "вони (ж.)"),
    ("אֵלֶּה", "ele", "these", "ці"),
    ("אֵלּוּ", "elu", "these (f)", "ці"),
    ("הַזֶּה", "hazeh", "this (m)", "цей"),
    ("הַזֹּאת", "hazot", "this (f)", "ця"),
    ("הַהוּא", "hahu", "that (m)", "той"),
    ("הַהִיא", "hahi", "that (f)", "та"),
    ("כָּאן", "kan", "here", "тут"),
    ("פֹּה", "po", "here", "тут"),
    ("שָׁם", "sham", "there", "там"),
    ("אֵיפֹה", "eifo", "where", "де"),
    ("לְאָן", "le'an", "where to", "куди"),
    ("מֵאַיִן", "me'ayin", "from where", "звідки"),
    ("כָּכָה", "kakha", "so; like that", "так"),
    ("כָּךְ", "kakh", "so; thus", "так"),
    ("אַחֵר", "akher", "other (m)", "інший"),
    ("אַחֶרֶת", "akheret", "other (f)", "інша"),
    ("עַצְמִי", "atzmi", "myself", "сам"),
    ("מִישֶׁהוּ", "mishehu", "someone", "хтось"),
    ("מַשֶּׁהוּ", "mashehu", "something", "щось"),
    ("אַף אֶחָד", "af echad", "nobody", "ніхто"),
    ("שׁוּם דָּבָר", "shum davar", "nothing", "нічого"),
    ("כֻּלָּם", "kulam", "everyone", "всі"),
    ("הַכֹּל", "hakol", "everything", "все"),
]

QUESTIONS_QUANTIFIERS = [
    ("מַה", "ma", "what", "що"),
    ("מָה", "ma", "what", "що"),
    ("מִי", "mi", "who", "хто"),
    ("אֵיךְ", "eikh", "how", "як"),
    ("מָתַי", "matai", "when", "коли"),
    ("לָמָּה", "lama", "why", "чому"),
    ("מַדּוּעַ", "madua", "why", "чому"),
    ("אֵיזֶה", "eizeh", "which (m)", "який"),
    ("אֵיזוֹ", "eizo", "which (f)", "яка"),
    ("הַאִם", "ha'im", "whether (yes/no marker)", "чи"),
    ("הַרְבֵּה", "harbe", "many; a lot", "багато"),
    ("מְעַט", "me'at", "few; little", "мало"),
    ("מְעַט מְעַט", "me'at me'at", "little by little", "потроху"),
    ("מַסְפִּיק", "maspik", "enough", "достатньо"),
    ("יוֹתֵר", "yoter", "more", "більше"),
    ("פָּחוֹת", "pachot", "less", "менше"),
    ("הַכִּי", "haki", "the most", "найбільше"),
    ("בְּיוֹתֵר", "beyoter", "most; extremely", "найбільш"),
    ("כָּל", "kol", "every; all", "кожен; весь"),
    ("שׁוּם", "shum", "any; no", "жоден"),
    ("אֵיזֶשֶׁהוּ", "eizeshehu", "some kind of (m)", "якийсь"),
    ("אֵיזוֹשֶׁהִי", "eizoshehi", "some kind of (f)", "якась"),
]

VERBS = [
    ("לִהְיוֹת", "lihyot", "to be", "бути"),
    ("יָכוֹל", "yakhol", "can; able", "можу; можливий"),
    ("לָבוֹא", "lavo", "to come", "приходити"),
    ("לָלֶכֶת", "lalekhet", "to go; walk", "іти"),
    ("לְהִיכָּנֵס", "lehikanes", "to enter", "входити"),
    ("לָצֵאת", "latzet", "to exit", "виходити"),
    ("לַעֲלוֹת", "la'alot", "to go up", "підніматися"),
    ("לָרֶדֶת", "laredet", "to go down", "спускатися"),
    ("לִרְאוֹת", "lirot", "to see", "бачити"),
    ("לִשְׁמֹעַ", "lishmoa", "to hear", "чути"),
    ("לְהִסְתַּכֵּל", "lehistakel", "to look at", "дивитися"),
    ("לְהַקְשִׁיב", "lehakshiv", "to listen", "слухати"),
    ("לְדַבֵּר", "ledaber", "to speak", "говорити"),
    ("לוֹמַר", "lomar", "to say", "казати"),
    ("לְהַגִּיד", "lehagid", "to say; tell", "сказати"),
    ("לַעֲנוֹת", "la'anot", "to answer", "відповідати"),
    ("לִשְׁאֹל", "lish'ol", "to ask", "питати"),
    ("לִקְרֹא", "likro", "to read; call", "читати"),
    ("לִכְתֹּב", "likhtov", "to write", "писати"),
    ("לְחַפֵּשׂ", "lechapes", "to search", "шукати"),
    ("לִמְצֹא", "limtzo", "to find", "знаходити"),
    ("לַעֲשׂוֹת", "la'asot", "to do; make", "робити"),
    ("לָדַעַת", "lada'at", "to know (fact)", "знати"),
    ("לְהַכִּיר", "lehakir", "to be acquainted with", "знати (когось)"),
    ("לְהָבִין", "lehavin", "to understand", "розуміти"),
    ("לַחְשֹׁב", "lachshov", "to think", "думати"),
    ("לְהַרְגִּישׁ", "lehargish", "to feel", "відчувати"),
    ("לִזְכֹּר", "lizkor", "to remember", "пам'ятати"),
    ("לִשְׁכֹּחַ", "lishkoach", "to forget", "забувати"),
    ("לִלְמֹד", "lilmod", "to study; learn", "вчити"),
    ("לְלַמֵּד", "lelamed", "to teach", "вчити (когось)"),
    ("לֶאֱכֹל", "le'echol", "to eat", "їсти"),
    ("לִשְׁתּוֹת", "lishtot", "to drink", "пити"),
    ("לִישֹׁן", "lishon", "to sleep", "спати"),
    ("לָקוּם", "lakum", "to get up", "вставати"),
    ("לִשְׁכַּב", "lishkav", "to lie down", "лежати"),
    ("לָשֶׁבֶת", "lashevet", "to sit", "сидіти"),
    ("לַעֲמֹד", "la'amod", "to stand", "стояти"),
    ("לָרוּץ", "larutz", "to run", "бігти"),
    ("לְבַשֵּׁל", "levashel", "to cook", "готувати"),
    ("לֶאֱפוֹת", "le'efot", "to bake", "пекти"),
    ("לִקְנוֹת", "liknot", "to buy", "купувати"),
    ("לִמְכֹּר", "limkor", "to sell", "продавати"),
    ("לְשַׁלֵּם", "leshalem", "to pay", "платити"),
    ("לָתֵת", "latet", "to give", "давати"),
    ("לָקַחַת", "lakachat", "to take", "брати"),
    ("לְקַבֵּל", "lekabel", "to receive", "отримувати"),
    ("לְהָבִיא", "lehavi", "to bring", "приносити"),
    ("לְהַחֲזִיר", "lehachzir", "to return (something)", "повертати"),
    ("לַעֲזֹר", "la'azor", "to help", "допомагати"),
    ("לְבַקֵּשׁ", "levakesh", "to request", "просити"),
    ("לְהַזְמִין", "lehazmin", "to invite; order", "запрошувати; замовляти"),
    ("לֶאֱהֹב", "le'ehov", "to love", "любити"),
    ("לִשְׂנֹא", "lisno", "to hate", "ненавидіти"),
    ("לִצְחֹק", "litzchok", "to laugh", "сміятися"),
    ("לִבְכּוֹת", "livkot", "to cry", "плакати"),
    ("לְחַיֵּךְ", "lechayekh", "to smile", "усміхатися"),
    ("לְהִתְרַגֵּשׁ", "lehitragesh", "to get excited", "хвилюватися"),
    ("לְהִתְעַצְבֵּן", "lehit'atzben", "to get annoyed", "дратуватися"),
    ("לִכְעֹס", "lich'os", "to be angry", "сердитися"),
    ("לְבַקֵּר", "levaker", "to visit", "відвідувати"),
    ("לִפְגֹּשׁ", "lifgosh", "to meet", "зустрічати"),
    ("לְהִתְקַשֵּׁר", "lehitkasher", "to call (phone)", "дзвонити"),
    ("לְשַׂחֵק", "lesachek", "to play (game)", "грати"),
    ("לְנַגֵּן", "lenagen", "to play (instrument)", "грати (на)"),
    ("לָשִׁיר", "lashir", "to sing", "співати"),
    ("לִרְקֹד", "lirkod", "to dance", "танцювати"),
    ("לִשְׂחוֹת", "liskhot", "to swim", "плавати"),
    ("לִנְסֹעַ", "linsoa", "to travel; drive", "їхати"),
    ("לָטוּס", "latus", "to fly", "літати"),
    ("לַחֲזֹר", "lachazor", "to return; come back", "повертатися"),
    ("לְחַכּוֹת", "lechakot", "to wait", "чекати"),
    ("לְהַתְחִיל", "lehat'chil", "to begin", "починати"),
    ("לִגְמֹר", "ligmor", "to finish", "закінчувати"),
    ("לְסַיֵּם", "lesayem", "to conclude", "завершувати"),
    ("לְהַמְשִׁיךְ", "lehamshikh", "to continue", "продовжувати"),
    ("לְהַפְסִיק", "lehafsik", "to stop", "переставати"),
    ("לַעֲצֹר", "la'atzor", "to halt; arrest", "зупиняти"),
    ("לִפְתֹּחַ", "liftoach", "to open", "відкривати"),
    ("לִסְגֹּר", "lisgor", "to close", "закривати"),
    ("לִשְׁבֹּר", "lishbor", "to break", "ламати"),
    ("לְתַקֵּן", "letaken", "to repair", "лагодити"),
    ("לִבְנוֹת", "livnot", "to build", "будувати"),
    ("לַהֲרֹס", "laharos", "to destroy", "руйнувати"),
    ("לְנַקּוֹת", "lenakot", "to clean", "прибирати"),
    ("לִשְׁטֹף", "lishtof", "to rinse; wash", "мити"),
    ("לְכַבֵּס", "lechabes", "to launder", "прати"),
    ("לְגַהֵץ", "legahetz", "to iron", "прасувати"),
    ("לַחְתֹּךְ", "lachtokh", "to cut", "різати"),
    ("לִתְפֹּר", "litpor", "to sew", "шити"),
    ("לְצַיֵּר", "letzayer", "to draw", "малювати"),
    ("לְצַלֵּם", "letzalem", "to photograph", "фотографувати"),
    ("לְהַסְבִּיר", "lehasbir", "to explain", "пояснювати"),
    ("לְסַפֵּר", "lesaper", "to tell", "розповідати"),
    ("לַחֲלֹם", "lachalom", "to dream", "мріяти; снити"),
    ("לְקַוּוֹת", "lekavot", "to hope", "сподіватися"),
    ("לְהַאֲמִין", "leha'amin", "to believe", "вірити"),
    ("לְשַׁכְנֵעַ", "leshakhneya", "to convince", "переконувати"),
    ("לְהַחְלִיט", "lehachlit", "to decide", "вирішувати"),
    ("לְנַסּוֹת", "lenasot", "to try", "пробувати"),
    ("לְהַצְלִיחַ", "lehatzliach", "to succeed", "досягати успіху"),
    ("לְהִתְכּוֹנֵן", "lehitkonen", "to prepare", "готуватися"),
    ("לְהַזְכִּיר", "lehazkir", "to mention; remind", "нагадувати"),
    ("לְהַצִּיעַ", "lehatzia", "to offer; suggest", "пропонувати"),
    ("לְהַזְהִיר", "lehazhir", "to warn", "попереджати"),
    ("לְהַסְכִּים", "lehaskim", "to agree", "погоджуватися"),
    ("לְהִתְנַגֵּד", "lehitnaged", "to oppose", "заперечувати"),
    ("לִרְצוֹת", "lirtzot", "to want", "хотіти"),
    ("לִצְרֹךְ", "litzrokh", "to need", "потребувати"),
    ("צָרִיךְ", "tzarikh", "needs; should", "треба"),
    ("מֻכְרָח", "mukhrach", "must", "мусить"),
    ("אָסוּר", "asur", "forbidden", "заборонено"),
    ("מֻתָּר", "mutar", "permitted", "дозволено"),
    ("לְהַרְשׁוֹת", "leharshot", "to permit", "дозволяти"),
    ("לֶאֱסֹר", "le'esor", "to forbid", "забороняти"),
    ("לְהִתְלַבֵּשׁ", "lehitlabesh", "to get dressed", "одягатися"),
    ("לְהִתְפַּשֵּׁט", "lehitpashet", "to undress", "роздягатися"),
    ("לְהִתְרַחֵץ", "lehitrachetz", "to bathe", "митися"),
    ("לְהִתְקַלֵּחַ", "lehitkaleach", "to shower", "приймати душ"),
    ("לְהִשְׁתַּמֵּשׁ", "lehishtamesh", "to use", "користуватися"),
    ("לְהַשְׁכִּיר", "lehaskir", "to rent out", "здавати в оренду"),
    ("לִשְׂכֹּר", "liskor", "to rent", "винаймати"),
    ("לְקַבֵּל הַחְלָטָה", "lekabel hachlata", "to make a decision", "ухвалювати рішення"),
    ("לְהוֹדִיעַ", "lehodia", "to inform", "повідомляти"),
    ("לְהוֹדוֹת", "lehodot", "to thank; admit", "дякувати; визнавати"),
    ("לְהִתְנַצֵּל", "lehitnatzel", "to apologize", "вибачатися"),
    ("לִסְלֹחַ", "lisloach", "to forgive", "пробачати"),
    ("לְהַרְוִיחַ", "leharviach", "to earn", "заробляти"),
    ("לְהוֹצִיא", "lehotzi", "to take out; spend", "виносити; витрачати"),
    ("לְהַכְנִיס", "lehakhnis", "to bring in", "вносити"),
    ("לְעַזֹב", "la'azov", "to leave", "залишати"),
    ("לַחֲגֹג", "lachagog", "to celebrate", "святкувати"),
    ("לְהַזְמִין אוֹרְחִים", "lehazmin orchim", "to host guests", "запрошувати гостей"),
    ("לְהִתְנַהֵג", "lehitnaheg", "to behave", "поводитися"),
    ("לְהַחְלִיף", "lehachlif", "to change; exchange", "змінювати; обмінювати"),
    ("לְשַׁנּוֹת", "leshanot", "to change", "змінювати"),
    ("לְהִשְׁתַּנּוֹת", "lehishtanot", "to change (intr.)", "змінюватися"),
    ("לִגְדֹּל", "ligdol", "to grow", "рости"),
    ("לְהִתְפַּתֵּחַ", "lehitpateach", "to develop (intr.)", "розвиватися"),
    ("לְפַתֵּחַ", "lefateach", "to develop (tr.)", "розвивати"),
    ("לְבַלּוֹת", "levalot", "to spend time", "проводити час"),
    ("לִמְהֹר", "limhor", "to hurry", "поспішати"),
    ("לְמַהֵר", "lemaher", "to hurry", "поспішати"),
    ("לְאַחֵר", "le'acher", "to be late", "запізнюватися"),
    ("לְהַסְפִּיק", "lehaspik", "to manage in time", "встигати"),
]

ADJECTIVES = [
    ("טוֹב", "tov", "good", "хороший"),
    ("רַע", "ra", "bad", "поганий"),
    ("יָפֶה", "yafe", "beautiful", "гарний"),
    ("מְכֹעָר", "mekho'ar", "ugly", "потворний"),
    ("חָדָשׁ", "chadash", "new", "новий"),
    ("יָשָׁן", "yashan", "old (thing)", "старий"),
    ("זָקֵן", "zaken", "old (person)", "літній"),
    ("צָעִיר", "tza'ir", "young", "молодий"),
    ("גָּדוֹל", "gadol", "big", "великий"),
    ("קָטָן", "katan", "small", "малий"),
    ("אָרֹךְ", "arokh", "long", "довгий"),
    ("קָצָר", "katzar", "short", "короткий"),
    ("גָּבוֹהַּ", "gavoah", "tall; high", "високий"),
    ("נָמוּךְ", "namukh", "short; low", "низький"),
    ("רָחָב", "rachav", "wide", "широкий"),
    ("צַר", "tzar", "narrow", "вузький"),
    ("עָבֶה", "aveh", "thick", "товстий"),
    ("דַּק", "dak", "thin", "тонкий"),
    ("כָּבֵד", "kaved", "heavy", "важкий"),
    ("קַל", "kal", "light; easy", "легкий"),
    ("חָזָק", "chazak", "strong", "сильний"),
    ("חַלָּשׁ", "chalash", "weak", "слабкий"),
    ("מָלֵא", "male", "full", "повний"),
    ("רֵיק", "reik", "empty", "порожній"),
    ("חַם", "cham", "hot", "гарячий"),
    ("קַר", "kar", "cold", "холодний"),
    ("חָמִים", "chamim", "warm", "теплий"),
    ("קָרִיר", "karir", "cool", "прохолодний"),
    ("יָבֵשׁ", "yavesh", "dry", "сухий"),
    ("רָטֹב", "ratov", "wet", "мокрий"),
    ("נָקִי", "naki", "clean", "чистий"),
    ("מְלֻכְלָךְ", "melukhlakh", "dirty", "брудний"),
    ("מָהִיר", "mahir", "fast", "швидкий"),
    ("אִטִּי", "iti", "slow", "повільний"),
    ("שָׂמֵחַ", "sameach", "happy", "веселий"),
    ("עָצוּב", "atzuv", "sad", "сумний"),
    ("כּוֹעֵס", "ko'es", "angry", "сердитий"),
    ("מְבֻלְבָּל", "mevulbal", "confused", "розгублений"),
    ("עָיֵף", "ayef", "tired", "втомлений"),
    ("רָעֵב", "ra'ev", "hungry", "голодний"),
    ("צָמֵא", "tzame", "thirsty", "спраглий"),
    ("שָׂבֵעַ", "savea", "full (after food)", "ситий"),
    ("חוֹלֶה", "choleh", "sick", "хворий"),
    ("בָּרִיא", "bari", "healthy", "здоровий"),
    ("חָשׁוּב", "chashuv", "important", "важливий"),
    ("מְעַנְיֵן", "me'anyen", "interesting", "цікавий"),
    ("מְשַׁעֲמֵם", "mesha'amem", "boring", "нудний"),
    ("קָשֶׁה", "kashe", "difficult", "важкий (тяжкий)"),
    ("פָּשׁוּט", "pashut", "simple", "простий"),
    ("מְסֻבָּךְ", "mesubakh", "complicated", "складний"),
    ("מְפֻרְסָם", "mefursam", "famous", "відомий"),
    ("עָשִׁיר", "ashir", "rich", "багатий"),
    ("עָנִי", "ani", "poor", "бідний"),
    ("אֲמִיתִי", "amiti", "real; true", "справжній"),
    ("שֶׁקֶר", "sheker", "false; a lie", "брехня"),
    ("נָכוֹן", "nakhon", "correct", "правильний"),
    ("שָׁגוּי", "shagui", "wrong", "хибний"),
    ("מַתְאִים", "matim", "suitable", "придатний"),
    ("שָׁוֶה", "shave", "equal; worth", "рівний; вартий"),
    ("שׁוֹנֶה", "shoneh", "different", "різний"),
    ("דּוֹמֶה", "domeh", "similar", "схожий"),
    ("מְשֻׁתָּף", "meshutaf", "shared; common", "спільний"),
    ("חַי", "chai", "alive", "живий"),
    ("מֵת", "met", "dead", "мертвий"),
    ("שָׁלֵם", "shalem", "whole", "цілий"),
    ("שָׁבוּר", "shavur", "broken", "зламаний"),
    ("חָפְשִׁי", "chofshi", "free", "вільний"),
    ("תָּפוּס", "tafus", "occupied", "зайнятий"),
    ("מָתוֹק", "matok", "sweet", "солодкий"),
    ("מַר", "mar", "bitter", "гіркий"),
    ("חָמוּץ", "chamutz", "sour", "кислий"),
    ("חָרִיף", "charif", "spicy", "гострий"),
    ("טָעִים", "ta'im", "delicious", "смачний"),
    ("בָּשֵׁל", "bashel", "ripe", "стиглий"),
    ("שָׁקֵט", "shaket", "quiet", "тихий"),
    ("רוֹעֵשׁ", "ro'esh", "noisy", "шумний"),
    ("בָּהִיר", "bahir", "bright", "світлий"),
    ("כֵּהֶה", "keheh", "dark (color)", "темний"),
    ("חָכָם", "chakham", "smart", "розумний"),
    ("טִפֵּשׁ", "tipesh", "stupid", "дурний"),
    ("נֶחְמָד", "nechmad", "nice", "милий"),
    ("אַדִּיב", "adiv", "polite", "ввічливий"),
    ("גַּס", "gas", "rude", "грубий"),
    ("נָדִיב", "nadiv", "generous", "щедрий"),
    ("קַמְצָן", "kamtzan", "stingy", "скнара"),
    ("אַמִּיץ", "amitz", "brave", "сміливий"),
    ("פַּחְדָן", "pachdan", "coward", "боягуз"),
    ("בָּטוּחַ", "batuach", "safe; certain", "безпечний; впевнений"),
    ("מְסֻכָּן", "mesukan", "dangerous", "небезпечний"),
    ("רָצִינִי", "retzini", "serious", "серйозний"),
    ("מַצְחִיק", "matzchik", "funny", "смішний"),
    ("עֲדִין", "adin", "gentle; delicate", "ніжний"),
    ("גַּס רוּחַ", "gas ruach", "rude (in spirit)", "хам"),
    ("עָקֵב", "aqev", "stubborn", "впертий"),
    ("עַצְלָן", "atzlan", "lazy", "лінивий"),
    ("חָרוּץ", "charutz", "diligent", "старанний"),
    ("מְעַט", "me'at", "few", "мало"),
    ("רַבִּים", "rabim", "many", "багато"),
    ("עִקָּרִי", "ikari", "main; principal", "головний"),
    ("רָגִיל", "ragil", "usual; ordinary", "звичайний"),
    ("מְיֻחָד", "meyuchad", "special", "особливий"),
    ("נוֹרָא", "nora", "terrible", "жахливий"),
    ("נֶהְדָּר", "nehedar", "wonderful", "чудовий"),
    ("נָדִיר", "nadir", "rare", "рідкісний"),
    ("שָׁכִיחַ", "shakhiach", "common; frequent", "поширений"),
]

COLORS = [
    ("כָּתֹם", "katom", "orange", "помаранчевий"),
    ("וָרֹד", "varod", "pink", "рожевий"),
    ("אָפֹר", "afor", "gray", "сірий"),
    ("חוּם", "chum", "brown", "коричневий"),
    ("סָגֹל", "sagol", "purple", "фіолетовий"),
    ("זָהָב", "zahav", "gold", "золотий"),
    ("שָׁקוּף", "shakuf", "transparent", "прозорий"),
    ("בֵּז'", "bezh", "beige", "бежевий"),
    ("טֻרְקִיז", "turkiz", "turquoise", "бірюзовий"),
    ("בּוּרְגּוּנְדִי", "burgundi", "burgundy", "бордовий"),
]

TIME = [
    ("אֶתְמוֹל", "etmol", "yesterday", "вчора"),
    ("הַיּוֹם", "hayom", "today", "сьогодні"),
    ("מָחָר", "machar", "tomorrow", "завтра"),
    ("שִׁלְשׁוֹם", "shilshom", "day before yesterday", "позавчора"),
    ("מָחֳרָתַיִם", "mochrotayim", "day after tomorrow", "післязавтра"),
    ("בֹּקֶר", "boker", "morning", "ранок"),
    ("צָהֳרַיִם", "tzohorayim", "noon", "полудень"),
    ("אַחַר הַצָּהֳרַיִם", "achar hatzohorayim", "afternoon", "після обіду"),
    ("עֶרֶב", "erev", "evening", "вечір"),
    ("לַיְלָה", "layla", "night", "ніч"),
    ("חֲצוֹת", "chatzot", "midnight", "опівніч"),
    ("שָׁבוּעַ", "shavua", "week", "тиждень"),
    ("חֹדֶשׁ", "chodesh", "month", "місяць"),
    ("שָׁנָה", "shana", "year", "рік"),
    ("שָׁעָה", "sha'a", "hour", "година"),
    ("דַּקָּה", "daka", "minute", "хвилина"),
    ("שְׁנִיָּה", "shniya", "second", "секунда"),
    ("רֶגַע", "rega", "moment", "мить"),
    ("זְמַן", "zman", "time", "час"),
    ("תָּמִיד", "tamid", "always", "завжди"),
    ("אַף פַּעַם", "af pa'am", "never", "ніколи"),
    ("לִפְעָמִים", "lif'amim", "sometimes", "іноді"),
    ("פַּעַם", "pa'am", "once; a time", "раз"),
    ("פַּעֲמַיִם", "pa'amayim", "twice", "двічі"),
    ("אֶמְצַע", "emtza", "middle", "середина"),
    ("סוֹף", "sof", "end", "кінець"),
    ("הַתְחָלָה", "hatchala", "beginning", "початок"),
    ("מֻקְדָּם", "mukdam", "early", "рано"),
    ("מְאֻחָר", "me'uchar", "late", "пізно"),
    ("עַכְשָׁו", "akhshav", "now", "зараз"),
    ("אַחַר כָּךְ", "achar kakh", "afterwards", "потім"),
    ("לִפְנֵי כֵן", "lifnei khen", "before that", "до того"),
    ("מִיָּד", "miyad", "immediately", "негайно"),
    ("בְּקָרוֹב", "bekarov", "soon", "скоро"),
    ("לְאַט", "le'at", "slowly", "повільно"),
    ("מַהֵר", "maher", "quickly", "швидко"),
    ("יוֹם רִאשׁוֹן", "yom rishon", "Sunday", "неділя"),
    ("יוֹם שֵׁנִי", "yom sheni", "Monday", "понеділок"),
    ("יוֹם שְׁלִישִׁי", "yom shlishi", "Tuesday", "вівторок"),
    ("יוֹם רְבִיעִי", "yom revii", "Wednesday", "середа"),
    ("יוֹם חֲמִישִׁי", "yom chamishi", "Thursday", "четвер"),
    ("יוֹם שִׁשִּׁי", "yom shishi", "Friday", "п'ятниця"),
    ("שַׁבָּת", "shabbat", "Saturday; Sabbath", "субота"),
    ("אָבִיב", "aviv", "spring", "весна"),
    ("קַיִץ", "kayitz", "summer", "літо"),
    ("סְתָו", "stav", "autumn", "осінь"),
    ("חֹרֶף", "choref", "winter", "зима"),
    ("יָנוּאָר", "yanuar", "January", "січень"),
    ("פֶבְּרוּאָר", "februar", "February", "лютий"),
    ("מֶרְץ", "merts", "March", "березень"),
    ("אַפְּרִיל", "april", "April", "квітень"),
    ("מַאי", "mai", "May", "травень"),
    ("יוּנִי", "yuni", "June", "червень"),
    ("יוּלִי", "yuli", "July", "липень"),
    ("אוֹגוּסְט", "ogust", "August", "серпень"),
    ("סֶפְּטֶמְבֶּר", "september", "September", "вересень"),
    ("אוֹקְטוֹבֶּר", "oktober", "October", "жовтень"),
    ("נוֹבֶמְבֶּר", "november", "November", "листопад"),
    ("דֶּצֶמְבֶּר", "detsember", "December", "грудень"),
    ("חַג", "chag", "holiday", "свято"),
    ("יוֹם הֻלֶּדֶת", "yom huledet", "birthday", "день народження"),
    ("שָׁעוֹן", "sha'on", "clock; watch", "годинник"),
    ("לוּחַ שָׁנָה", "luach shana", "calendar", "календар"),
]

FAMILY = [
    ("אָב", "av", "father", "батько"),
    ("אֵם", "em", "mother", "мати"),
    ("בֵּן", "ben", "son", "син"),
    ("בַּת", "bat", "daughter", "донька"),
    ("אָח", "ach", "brother", "брат"),
    ("אָחוֹת", "achot", "sister", "сестра"),
    ("סָבָא", "saba", "grandfather", "дідусь"),
    ("סָבְתָּא", "savta", "grandmother", "бабуся"),
    ("נֶכֶד", "nekhed", "grandson", "онук"),
    ("נֶכְדָּה", "nekhda", "granddaughter", "онука"),
    ("דּוֹד", "dod", "uncle", "дядько"),
    ("דּוֹדָה", "doda", "aunt", "тітка"),
    ("אַחְיָן", "achyan", "nephew", "племінник"),
    ("אַחְיָנִית", "achyanit", "niece", "племінниця"),
    ("בֶּן דּוֹד", "ben dod", "cousin (m)", "двоюрідний брат"),
    ("בַּת דּוֹדָה", "bat doda", "cousin (f)", "двоюрідна сестра"),
    ("חָתָן", "chatan", "groom; son-in-law", "наречений; зять"),
    ("כַּלָּה", "kala", "bride; daughter-in-law", "наречена; невістка"),
    ("חָמוֹת", "chamot", "mother-in-law", "теща; свекруха"),
    ("חָם", "cham", "father-in-law", "тесть; свекор"),
    ("בַּעַל", "ba'al", "husband", "чоловік"),
    ("הוֹרֶה", "horeh", "parent", "батько/мати"),
    ("הוֹרִים", "horim", "parents", "батьки"),
    ("תִּינוֹק", "tinok", "baby", "немовля"),
    ("תִּינוֹקֶת", "tinoket", "baby girl", "немовля (ж.)"),
    ("נַעַר", "na'ar", "boy; youth", "хлопець"),
    ("נַעֲרָה", "na'ara", "girl; youth", "дівчина"),
    ("חָבֵר", "chaver", "friend (m)", "друг"),
    ("חֲבֵרָה", "chavera", "friend (f)", "подруга"),
    ("שָׁכֵן", "shakhen", "neighbor", "сусід"),
    ("שְׁכֵנָה", "shkhena", "neighbor (f)", "сусідка"),
    ("מִשְׁפָּחָה", "mishpacha", "family", "родина"),
    ("קְרוֹב מִשְׁפָּחָה", "krov mishpacha", "relative", "родич"),
    ("יָתוֹם", "yatom", "orphan", "сирота"),
    ("אַלְמָנָה", "almana", "widow", "вдова"),
    ("גָּרוּשׁ", "garush", "divorced", "розлучений"),
    ("רַוָּק", "ravak", "bachelor", "холостяк"),
    ("זוּג", "zug", "couple; pair", "пара"),
]

BODY_HEALTH = [
    ("פָּנִים", "panim", "face", "обличчя"),
    ("עַיִן", "ayin", "eye", "око"),
    ("אֹזֶן", "ozen", "ear", "вухо"),
    ("אַף", "af", "nose", "ніс"),
    ("פֶּה", "pe", "mouth", "рот"),
    ("שָׂפָה", "safa", "lip; language", "губа; мова"),
    ("לָשׁוֹן", "lashon", "tongue", "язик"),
    ("שֵׁן", "shen", "tooth", "зуб"),
    ("שִׁנַּיִם", "shinayim", "teeth", "зуби"),
    ("כָּתֵף", "katef", "shoulder", "плече"),
    ("זְרוֹעַ", "zroa", "arm", "рука (плече)"),
    ("יָד", "yad", "hand", "рука"),
    ("אֶצְבַּע", "etzba", "finger", "палець"),
    ("מַרְפֵּק", "marpek", "elbow", "лікоть"),
    ("אֲגוּדָל", "agudal", "thumb", "великий палець"),
    ("צִפֹּרֶן", "tziporen", "nail", "ніготь"),
    ("חָזֶה", "chazeh", "chest", "груди"),
    ("גַּב", "gav", "back", "спина"),
    ("בֶּטֶן", "beten", "belly", "живіт"),
    ("מָתְנַיִם", "motnayim", "hips; waist", "стегна; талія"),
    ("רֶגֶל", "regel", "leg; foot", "нога"),
    ("בֶּרֶךְ", "berekh", "knee", "коліно"),
    ("קַרְסֹל", "karsol", "ankle", "щиколотка"),
    ("כַּף רֶגֶל", "kaf regel", "foot (sole)", "стопа"),
    ("לֵב", "lev", "heart", "серце"),
    ("רֵאָה", "rea", "lung", "легеня"),
    ("כִּלְיָה", "kilya", "kidney", "нирка"),
    ("קֵבָה", "keva", "stomach (organ)", "шлунок"),
    ("שֵׂעָר", "se'ar", "hair", "волосся"),
    ("עוֹר", "or", "skin", "шкіра"),
    ("עֶצֶם", "etzem", "bone", "кістка"),
    ("שְׁרִיר", "shrir", "muscle", "м'яз"),
    ("דָּם", "dam", "blood", "кров"),
    ("מֹחַ", "moach", "brain", "мозок"),
    ("מַחֲלָה", "machala", "disease", "хвороба"),
    ("שַׁפַּעַת", "shapaat", "flu", "грип"),
    ("צִנּוּן", "tzinun", "cold (illness)", "застуда"),
    ("חֹם", "chom", "fever; heat", "температура"),
    ("כְּאֵב", "ke'ev", "pain", "біль"),
    ("כְּאֵב רֹאשׁ", "ke'ev rosh", "headache", "головний біль"),
    ("שִׁעוּל", "shi'ul", "cough", "кашель"),
    ("בְּחִילָה", "bechila", "nausea", "нудота"),
    ("פֶּצַע", "petza", "wound", "рана"),
    ("שֶׁבֶר", "shever", "fracture", "перелом"),
    ("רוֹפֵא", "rofe", "doctor", "лікар"),
    ("בֵּית חוֹלִים", "beit cholim", "hospital", "лікарня"),
    ("מִרְפָּאָה", "mirpa'a", "clinic", "клініка"),
    ("תְּרוּפָה", "terufa", "medicine", "ліки"),
    ("בֵּית מִרְקַחַת", "beit mirkachat", "pharmacy", "аптека"),
    ("מַזְרֵק", "mazrek", "syringe", "шприц"),
    ("חִסּוּן", "chisun", "vaccination", "щеплення"),
    ("דִּיאֵטָה", "dieta", "diet", "дієта"),
    ("בְּרִיאוּת", "bri'ut", "health", "здоров'я"),
]

FOOD = [
    ("לֶחֶם", "lechem", "bread", "хліб"),
    ("חֶמְאָה", "chem'a", "butter", "масло"),
    ("גְּבִינָה", "gvina", "cheese", "сир"),
    ("בֵּיצָה", "beitza", "egg", "яйце"),
    ("חָלָב", "chalav", "milk", "молоко"),
    ("יוֹגוּרְט", "yogurt", "yogurt", "йогурт"),
    ("שַׁמֶּנֶת", "shamenet", "sour cream", "сметана"),
    ("שֶׁמֶן", "shemen", "oil", "олія"),
    ("מֶלַח", "melach", "salt", "сіль"),
    ("פִּלְפֵּל", "pilpel", "pepper", "перець"),
    ("סֻכָּר", "sukar", "sugar", "цукор"),
    ("קֶמַח", "kemach", "flour", "борошно"),
    ("אֹרֶז", "orez", "rice", "рис"),
    ("פַּסְטָה", "pasta", "pasta", "макарони"),
    ("מָרָק", "marak", "soup", "суп"),
    ("סָלָט", "salat", "salad", "салат"),
    ("בָּשָׂר", "basar", "meat", "м'ясо"),
    ("עוֹף", "of", "chicken", "курка"),
    ("בְּשַׂר בָּקָר", "bsar bakar", "beef", "яловичина"),
    ("בְּשַׂר טָלֶה", "bsar tale", "lamb", "ягнятина"),
    ("נַקְנִיק", "naknik", "sausage", "ковбаса"),
    ("דָּג מָלוּחַ", "dag maluach", "salted fish", "солона риба"),
    ("פֵּרוֹת", "perot", "fruits", "фрукти"),
    ("יְרָקוֹת", "yerakot", "vegetables", "овочі"),
    ("תַּפּוּחַ", "tapuach", "apple", "яблуко"),
    ("בָּנָנָה", "banana", "banana", "банан"),
    ("תַּפּוּז", "tapuz", "orange", "апельсин"),
    ("לִימוֹן", "limon", "lemon", "лимон"),
    ("עֲנָבִים", "anavim", "grapes", "виноград"),
    ("אֲבַטִּיחַ", "avatiach", "watermelon", "кавун"),
    ("מֵלוֹן", "melon", "melon", "диня"),
    ("אֲגָס", "agas", "pear", "груша"),
    ("אֲפַרְסֵק", "afarsek", "peach", "персик"),
    ("שְׁזִיף", "shezif", "plum", "слива"),
    ("דֻּבְדְּבָן", "duvdevan", "cherry", "вишня"),
    ("תּוּת", "tut", "strawberry", "полуниця"),
    ("פֵּרֵר", "perer", "berry", "ягода"),
    ("עַגְבָנִיָּה", "agvaniya", "tomato", "помідор"),
    ("מְלָפְפוֹן", "melafefon", "cucumber", "огірок"),
    ("גֶּזֶר", "gezer", "carrot", "морква"),
    ("בָּצָל", "batzal", "onion", "цибуля"),
    ("שׁוּם", "shum", "garlic", "часник"),
    ("תַּפּוּחַ אֲדָמָה", "tapuach adama", "potato", "картопля"),
    ("פִּטְרִיָּה", "pitriya", "mushroom", "гриб"),
    ("חַסָּה", "chasa", "lettuce", "салат-латук"),
    ("כְּרוּב", "kruv", "cabbage", "капуста"),
    ("פִּלְפֵּל יָרֹק", "pilpel yarok", "green pepper", "зелений перець"),
    ("חָצִיל", "chatzil", "eggplant", "баклажан"),
    ("קוּלִי", "kuli", "kohlrabi", "кольрабі"),
    ("עוּגָה", "uga", "cake", "торт"),
    ("עוּגִיָּה", "ugiya", "cookie", "печиво"),
    ("גְּלִידָה", "glida", "ice cream", "морозиво"),
    ("שׁוֹקוֹלָד", "shokolad", "chocolate", "шоколад"),
    ("דְּבַשׁ", "dvash", "honey", "мед"),
    ("רִבָּה", "riba", "jam", "варення"),
    ("מַיִם", "mayim", "water", "вода"),
    ("מִיץ", "mitz", "juice", "сік"),
    ("קָפֶה", "kafeh", "coffee", "кава"),
    ("תֵּה", "te", "tea", "чай"),
    ("יַיִן", "yayin", "wine", "вино"),
    ("בִּירָה", "bira", "beer", "пиво"),
    ("מַשְׁקֶה", "mashkeh", "drink", "напій"),
    ("אֲרוּחָה", "arucha", "meal", "трапеза"),
    ("אֲרוּחַת בֹּקֶר", "aruchat boker", "breakfast", "сніданок"),
    ("אֲרוּחַת צָהֳרַיִם", "aruchat tzohorayim", "lunch", "обід"),
    ("אֲרוּחַת עֶרֶב", "aruchat erev", "dinner", "вечеря"),
    ("מַתָּנָה", "matana", "gift", "подарунок"),
    ("צַלַּחַת", "tzalachat", "plate", "тарілка"),
    ("כּוֹס", "kos", "cup", "склянка"),
    ("סַכִּין", "sakin", "knife", "ніж"),
    ("מַזְלֵג", "mazleg", "fork", "виделка"),
    ("כַּף", "kaf", "spoon", "ложка"),
    ("מַפִּית", "mapit", "napkin", "серветка"),
    ("מַגֶּבֶת", "magevet", "towel", "рушник"),
]

CLOTHING = [
    ("בְּגָדִים", "begadim", "clothes", "одяг"),
    ("חֻלְצָה", "chultza", "shirt", "сорочка"),
    ("מִכְנָסַיִם", "mikhnasayim", "pants", "штани"),
    ("מִכְנְסֵי גִּ'ינְס", "mikhnesei jeans", "jeans", "джинси"),
    ("חֲצָאִית", "chatza'it", "skirt", "спідниця"),
    ("שִׂמְלָה", "simla", "dress", "сукня"),
    ("חֻלְצַת טְרִיקוֹ", "chultzat triko", "T-shirt", "футболка"),
    ("סְוֶדֶר", "sveder", "sweater", "светр"),
    ("מְעִיל", "me'il", "coat", "пальто"),
    ("גֶּ'קֶט", "jeket", "jacket", "куртка"),
    ("נַעֲלַיִם", "na'alayim", "shoes", "взуття"),
    ("מַגָּפַיִם", "magafayim", "boots", "чоботи"),
    ("סַנְדָּלִים", "sandalim", "sandals", "сандалі"),
    ("נַעֲלֵי סְפּוֹרְט", "na'alei sport", "sneakers", "кросівки"),
    ("גַּרְבַּיִם", "garbayim", "socks", "шкарпетки"),
    ("גַּרְבּוֹנִים", "garbonim", "tights", "колготки"),
    ("חֲגוֹרָה", "chagora", "belt", "пояс"),
    ("עֲנִיבָה", "aniva", "tie", "краватка"),
    ("צָעִיף", "tza'if", "scarf", "шарф"),
    ("כּוֹבַע", "kova", "hat", "капелюх"),
    ("כְּפָפוֹת", "kfafot", "gloves", "рукавички"),
    ("מִשְׁקָפַיִם", "mishkafayim", "glasses", "окуляри"),
    ("מִשְׁקְפֵי שֶׁמֶשׁ", "mishkefei shemesh", "sunglasses", "сонячні окуляри"),
    ("טַבַּעַת", "taba'at", "ring", "перстень"),
    ("שַׁרְשֶׁרֶת", "sharsheret", "necklace; chain", "ланцюжок"),
    ("עָגִיל", "agil", "earring", "сережка"),
    ("שָׁעוֹן יָד", "sha'on yad", "wristwatch", "наручний годинник"),
    ("חֲלִיפַת יָם", "chalifat yam", "swimsuit", "купальник"),
    ("פִּיגָ'מָה", "pijama", "pajamas", "піжама"),
    ("גּוּפִיָּה", "gufiya", "undershirt", "майка"),
    ("תַּחְתּוֹנִים", "tachtonim", "underwear", "білизна"),
    ("חֲזִיָּה", "chaziya", "bra", "бюстгальтер"),
    ("מַגֶּבֶת", "magevet", "towel", "рушник"),
    ("אֲרוֹן בְּגָדִים", "aron begadim", "wardrobe", "шафа"),
    ("מַטְרִיָּה", "matriya", "umbrella", "парасоля"),
]

HOME = [
    ("חֶדֶר", "cheder", "room", "кімната"),
    ("חֲדַר שֵׁנָה", "chadar shena", "bedroom", "спальня"),
    ("חֲדַר אֹכֶל", "chadar okhel", "dining room", "їдальня"),
    ("סָלוֹן", "salon", "living room", "вітальня"),
    ("מִטְבָּח", "mitbach", "kitchen", "кухня"),
    ("חֲדַר אַמְבַּטְיָה", "chadar ambatya", "bathroom", "ванна кімната"),
    ("שֵׁרוּתִים", "sherutim", "toilet", "туалет"),
    ("מִרְפֶּסֶת", "mirpeset", "balcony", "балкон"),
    ("מַסְדְּרוֹן", "masderon", "corridor", "коридор"),
    ("מַדְרֵגוֹת", "madregot", "stairs", "сходи"),
    ("מַעֲלִית", "ma'alit", "elevator", "ліфт"),
    ("דֶּלֶת", "delet", "door", "двері"),
    ("חַלּוֹן", "chalon", "window", "вікно"),
    ("רִצְפָּה", "ritzpa", "floor", "підлога"),
    ("תִּקְרָה", "tikra", "ceiling", "стеля"),
    ("קִיר", "kir", "wall", "стіна"),
    ("גָּג", "gag", "roof", "дах"),
    ("מִטָּה", "mita", "bed", "ліжко"),
    ("כִּסֵּא", "kise", "chair", "стілець"),
    ("שֻׁלְחָן", "shulchan", "table", "стіл"),
    ("סַפָּה", "sapa", "sofa", "диван"),
    ("כֻּרְסָה", "kursa", "armchair", "крісло"),
    ("מַדָּף", "madaf", "shelf", "полиця"),
    ("אֲרוֹן", "aron", "cabinet; closet", "шафа"),
    ("מְגֵרָה", "megera", "drawer", "шухляда"),
    ("שָׁטִיחַ", "shatiach", "rug", "килим"),
    ("וִילוֹן", "vilon", "curtain", "штора"),
    ("כָּרִית", "karit", "pillow", "подушка"),
    ("שְׂמִיכָה", "smikha", "blanket", "ковдра"),
    ("סָדִין", "sadin", "sheet", "простирадло"),
    ("מְנוֹרָה", "menora", "lamp", "лампа"),
    ("נוּרָה", "nura", "lightbulb", "лампочка"),
    ("מַזְגָּן", "mazgan", "air conditioner", "кондиціонер"),
    ("מְאַוְרֵר", "me'avrer", "fan", "вентилятор"),
    ("תַּנּוּר", "tanur", "oven", "пічка"),
    ("כִּירַיִם", "kirayim", "stove burners", "плита"),
    ("מִקְרָר", "mikrar", "refrigerator", "холодильник"),
    ("מַדִּיחַ כֵּלִים", "madiach kelim", "dishwasher", "посудомийка"),
    ("מְכוֹנַת כְּבִיסָה", "mekhonat kvisa", "washing machine", "пральна машина"),
    ("מִכְשִׁיר", "makhshir", "device", "пристрій"),
    ("טֶלֶוִיזְיָה", "televizya", "television", "телевізор"),
    ("רַדְיוֹ", "radyo", "radio", "радіо"),
    ("מַחְשֵׁב נַיָּד", "mach'shev nayad", "laptop", "ноутбук"),
    ("מַדְפֶּסֶת", "madpeset", "printer", "принтер"),
    ("כֶּבֶל", "kevel", "cable", "кабель"),
    ("מַטְעֵן", "mat'en", "charger", "зарядка"),
    ("חַלּוֹן רָאֲוָה", "chalon ra'ava", "shop window", "вітрина"),
]

CITY_PLACES = [
    ("רְחוֹב", "rechov", "street", "вулиця"),
    ("שְׂדֵרָה", "sdera", "avenue", "проспект"),
    ("כִּכָּר", "kikar", "square", "площа"),
    ("גִּשְׁרוֹן", "gishron", "small bridge", "місточок"),
    ("גֶּשֶׁר", "gesher", "bridge", "міст"),
    ("פַּארְק", "park", "park", "парк"),
    ("גַּן", "gan", "garden; kindergarten", "сад"),
    ("שׁוּק", "shuk", "market", "ринок"),
    ("חֲנוּת", "chanut", "shop", "магазин"),
    ("סוּפֶּרְמַרְקֶט", "supermarket", "supermarket", "супермаркет"),
    ("קַנְיוֹן", "kanyon", "mall", "торговий центр"),
    ("בֵּית קָפֶה", "beit kafe", "café", "кав'ярня"),
    ("מִסְעָדָה", "mis'ada", "restaurant", "ресторан"),
    ("מָלוֹן", "malon", "hotel", "готель"),
    ("דֹּאַר", "do'ar", "post (mail)", "пошта"),
    ("בַּנְק", "bank", "bank", "банк"),
    ("בֵּית סֵפֶר", "beit sefer", "school", "школа"),
    ("גַּן יְלָדִים", "gan yeladim", "kindergarten", "дитсадок"),
    ("אוּנִיבֶרְסִיטָה", "universita", "university", "університет"),
    ("סִפְרִיָּה", "sifriya", "library", "бібліотека"),
    ("מוּזֵיאוֹן", "muzeon", "museum", "музей"),
    ("תֵּאַטְרוֹן", "teatron", "theater", "театр"),
    ("קוֹלְנוֹעַ", "kolnoa", "cinema", "кіно"),
    ("אִצְטַדְיוֹן", "itztadyon", "stadium", "стадіон"),
    ("בְּרֵכָה", "brekha", "pool", "басейн"),
    ("חוֹף", "chof", "beach; shore", "пляж"),
    ("יָם", "yam", "sea", "море"),
    ("אֲגַם", "agam", "lake", "озеро"),
    ("נָהָר", "nahar", "river", "ріка"),
    ("הָר", "har", "mountain", "гора"),
    ("יַעַר", "ya'ar", "forest", "ліс"),
    ("שָׂדֶה", "sade", "field", "поле"),
    ("מִדְבָּר", "midbar", "desert", "пустеля"),
    ("עֵמֶק", "emek", "valley", "долина"),
    ("כְּפָר", "kfar", "village", "село"),
    ("מְקוֹם עֲבוֹדָה", "mekom avoda", "workplace", "робоче місце"),
    ("מִשְׂרָד", "misrad", "office", "офіс"),
    ("מִפְעָל", "mif'al", "factory", "фабрика"),
    ("תַּחֲנַת אוֹטוֹבּוּס", "tachanat otobus", "bus stop", "автобусна зупинка"),
    ("שְׂדֵה תְּעוּפָה", "sde te'ufa", "airport", "аеропорт"),
    ("נָמֵל", "namel", "port", "порт"),
    ("מִשְׁטָרָה", "mishtara", "police", "поліція"),
    ("מַכַּבֵּי אֵשׁ", "mekabei esh", "firefighters", "пожежники"),
    ("בֵּית כְּנֶסֶת", "beit knesset", "synagogue", "синагога"),
    ("כְּנֵסִיָּה", "kenesiya", "church", "церква"),
    ("מִסְגָּד", "misgad", "mosque", "мечеть"),
]

NATURE_WEATHER = [
    ("שֶׁמֶשׁ", "shemesh", "sun", "сонце"),
    ("יָרֵחַ", "yareach", "moon", "місяць"),
    ("כּוֹכָב", "kokhav", "star", "зірка"),
    ("שָׁמַיִם", "shamayim", "sky", "небо"),
    ("עָנָן", "anan", "cloud", "хмара"),
    ("גֶּשֶׁם", "geshem", "rain", "дощ"),
    ("שֶׁלֶג", "sheleg", "snow", "сніг"),
    ("בָּרָק", "barak", "lightning", "блискавка"),
    ("רַעַם", "ra'am", "thunder", "грім"),
    ("רוּחַ", "ruach", "wind; spirit", "вітер"),
    ("עָנָנִים", "ananim", "clouds", "хмари"),
    ("עָרְפֶל", "arpel", "fog", "туман"),
    ("טַל", "tal", "dew", "роса"),
    ("בָּרָד", "barad", "hail", "град"),
    ("מֶזֶג אֲוִיר", "mezeg avir", "weather", "погода"),
    ("אֲוִיר", "avir", "air", "повітря"),
    ("טֶמְפֶּרָטוּרָה", "temperatura", "temperature", "температура"),
    ("מַעֲלָה", "ma'ala", "degree", "градус"),
    ("חַשְׁמַל", "chashmal", "electricity", "електрика"),
    ("אֵשׁ", "esh", "fire", "вогонь"),
    ("עָשָׁן", "ashan", "smoke", "дим"),
    ("אֲדָמָה", "adama", "earth; soil", "земля; ґрунт"),
    ("חוֹל", "chol", "sand", "пісок"),
    ("אֶבֶן", "even", "stone", "камінь"),
    ("עֵץ", "etz", "tree; wood", "дерево"),
    ("עָלֶה", "ale", "leaf", "лист (рослини)"),
    ("פֶּרַח", "perach", "flower", "квітка"),
    ("שֹׁרֶשׁ", "shoresh", "root", "корінь"),
    ("עָנָף", "anaf", "branch", "гілка"),
    ("דֶּשֶׁא", "deshe", "grass", "трава"),
    ("צֶמַח", "tzemach", "plant", "рослина"),
    ("יָרֹק", "yarok", "green", "зелений"),
    ("נוֹף", "nof", "landscape; view", "пейзаж"),
    ("טֶבַע", "teva", "nature", "природа"),
    ("חַי", "chai", "living", "живий"),
    ("דּוֹמֵם", "domem", "inanimate", "неживий"),
    ("רַעַשׁ", "ra'ash", "noise", "шум"),
    ("צֵל", "tzel", "shadow; shade", "тінь"),
    ("אוֹר", "or", "light", "світло"),
    ("חֹשֶׁךְ", "choshekh", "darkness", "темрява"),
    ("מַעְיָן", "ma'ayan", "spring (water)", "джерело"),
    ("שֶׁטֶף", "shetef", "flow; flood", "потік"),
    ("גַּל", "gal", "wave", "хвиля"),
]

ANIMALS = [
    ("פָּרָה", "para", "cow", "корова"),
    ("שׁוֹר", "shor", "ox", "бик"),
    ("עֵז", "ez", "goat", "коза"),
    ("כֶּבֶשׂ", "keves", "sheep", "вівця"),
    ("חֲזִיר", "chazir", "pig", "свиня"),
    ("סוּס", "sus", "horse", "кінь"),
    ("חֲמוֹר", "chamor", "donkey", "осел"),
    ("גָּמָל", "gamal", "camel", "верблюд"),
    ("ארנב", "arnav", "rabbit", "кролик"),
    ("עַכְבָּר", "akhbar", "mouse", "миша"),
    ("חֻלְדָּה", "chulda", "rat", "щур"),
    ("צִפּוֹר", "tzipor", "bird", "птах"),
    ("יוֹנָה", "yona", "dove", "голуб"),
    ("נֶשֶׁר", "nesher", "eagle", "орел"),
    ("עוֹף", "of", "fowl", "птиця"),
    ("תַּרְנְגוֹל", "tarnegol", "rooster", "півень"),
    ("תַּרְנְגֹלֶת", "tarnegolet", "hen", "курка"),
    ("בַּרְבּוּר", "barbur", "swan", "лебідь"),
    ("דָּגִים", "dagim", "fish (pl.)", "риби"),
    ("נָחָשׁ", "nachash", "snake", "змія"),
    ("דְּבוֹרָה", "dvora", "bee", "бджола"),
    ("פַּרְפַּר", "parpar", "butterfly", "метелик"),
    ("יַתּוּשׁ", "yatush", "mosquito", "комар"),
    ("זְבוּב", "zvuv", "fly", "муха"),
    ("נְמָלָה", "nemala", "ant", "мураха"),
    ("עַכָּבִישׁ", "akavish", "spider", "павук"),
    ("צְפַרְדֵּעַ", "tzfardea", "frog", "жаба"),
    ("צָב", "tzav", "turtle", "черепаха"),
    ("פִּיל", "pil", "elephant", "слон"),
    ("דֻּב", "dov", "bear", "ведмідь"),
    ("זְאֵב", "ze'ev", "wolf", "вовк"),
    ("שׁוּעָל", "shu'al", "fox", "лисиця"),
    ("אַרְיֵה", "aryeh", "lion", "лев"),
    ("נָמֵר", "namer", "leopard", "леопард"),
    ("קוֹף", "kof", "monkey", "мавпа"),
    ("גִּ'ירָפָה", "jirafa", "giraffe", "жираф"),
]

WORK = [
    ("עֲבוֹדָה", "avoda", "work", "робота"),
    ("עוֹבֵד", "oved", "worker; employee (m)", "робітник"),
    ("עוֹבֶדֶת", "ovedet", "worker; employee (f)", "робітниця"),
    ("מְנַהֵל", "menahel", "manager", "керівник"),
    ("מְנַהֶלֶת", "menahelet", "manager (f)", "керівниця"),
    ("בַּעַל הַבַּיִת", "ba'al habayit", "owner; landlord", "власник"),
    ("מַעֲבִיד", "ma'avid", "employer", "роботодавець"),
    ("עָמִית", "amit", "colleague", "колега"),
    ("מַשְׂכֹּרֶת", "maskoret", "salary", "зарплата"),
    ("שָׂכָר", "sakhar", "wage; pay", "оплата"),
    ("מַס", "mas", "tax", "податок"),
    ("חוֹזֶה", "chozeh", "contract", "договір"),
    ("מִכְתָּב", "michtav", "letter", "лист"),
    ("פְּגִישָׁה", "pgisha", "meeting", "зустріч"),
    ("יְשִׁיבָה", "yeshiva", "session; meeting", "засідання"),
    ("פְּרוֹיֶקְט", "proyekt", "project", "проєкт"),
    ("מַטָּרָה", "matara", "goal", "мета"),
    ("תַּפְקִיד", "tafkid", "role; position", "посада"),
    ("מִקְצוֹעַ", "miktzoa", "profession", "професія"),
    ("חַקְלָאוּת", "chakla'ut", "agriculture", "сільське господарство"),
    ("תַּעֲשִׂיָּה", "ta'asiya", "industry", "промисловість"),
    ("מִסְחָר", "mischar", "commerce", "торгівля"),
    ("בַּנְקַאי", "bankai", "banker", "банкір"),
    ("עוֹרֵךְ דִּין", "orekh din", "lawyer", "адвокат"),
    ("שׁוֹפֵט", "shofet", "judge", "суддя"),
    ("מַהֲנְדֵּס", "mahandes", "engineer", "інженер"),
    ("טֶכְנַאי", "tekhnai", "technician", "технік"),
    ("מַדְעָן", "mad'an", "scientist", "вчений"),
    ("חוֹקֵר", "choker", "researcher", "дослідник"),
    ("אוֹמָן", "oman", "artist; craftsman", "майстер"),
    ("שַׂחְקָן", "sachkan", "actor; player", "актор; гравець"),
    ("זַמָּר", "zamar", "singer", "співак"),
    ("מוּזִיקַאי", "muzikai", "musician", "музикант"),
    ("צַלָּם", "tzalam", "photographer", "фотограф"),
    ("עִתּוֹנַאי", "itonai", "journalist", "журналіст"),
    ("סוֹפֵר", "sofer", "writer", "письменник"),
    ("מְשׁוֹרֵר", "meshorer", "poet", "поет"),
    ("מוֹרֶה", "moreh", "teacher (m)", "вчитель"),
    ("מוֹרָה", "mora", "teacher (f)", "вчителька"),
    ("מַרְצֶה", "martze", "lecturer", "лектор"),
    ("מַזְכִּיר", "mazkir", "secretary", "секретар"),
    ("נֶהָג", "nehag", "driver", "водій"),
    ("טַבָּח", "tabach", "cook", "кухар"),
    ("מֶלְצָר", "meltzar", "waiter", "офіціант"),
    ("מֶלְצָרִית", "meltzarit", "waitress", "офіціантка"),
    ("חַיָּל", "chayal", "soldier", "солдат"),
    ("שׁוֹטֵר", "shoter", "policeman", "поліцейський"),
    ("גַּנָּן", "ganan", "gardener", "садівник"),
    ("דָּוָּר", "davar", "postman", "листоноша"),
]

EDUCATION = [
    ("לִמּוּד", "limud", "study; learning", "навчання"),
    ("שִׁעוּר", "shi'ur", "lesson", "урок"),
    ("מִבְחָן", "mivchan", "test", "тест"),
    ("בְּחִינָה", "bechina", "exam", "іспит"),
    ("שִׁעוּרֵי בַּיִת", "shi'urei bayit", "homework", "домашнє завдання"),
    ("תַּלְמִיד", "talmid", "student (m)", "учень"),
    ("תַּלְמִידָה", "talmida", "student (f)", "учениця"),
    ("סְטוּדֶנְט", "student", "university student", "студент"),
    ("כִּתָּה", "kita", "class; classroom", "клас"),
    ("שִׂכְלוֹת", "skhelot", "abilities", "здібності"),
    ("יְדִיעָה", "yedi'a", "knowledge item; news item", "знання; повідомлення"),
    ("יֶדַע", "yeda", "knowledge", "знання"),
    ("חָכְמָה", "chokhma", "wisdom", "мудрість"),
    ("שָׂפָה", "safa", "language", "мова"),
    ("דִּקְדּוּק", "dikduk", "grammar", "граматика"),
    ("מִלָּה", "mila", "word", "слово"),
    ("מִשְׁפָּט", "mishpat", "sentence", "речення"),
    ("מַחְבֶּרֶת", "machberet", "notebook", "зошит"),
    ("עִפָּרוֹן", "iparon", "pencil", "олівець"),
    ("עֵט", "et", "pen", "ручка"),
    ("מַחַק", "machak", "eraser", "гумка"),
    ("סַרְגֵּל", "sargel", "ruler", "лінійка"),
    ("מִסְפָּרַיִם", "misparayim", "scissors", "ножиці"),
    ("דֶּבֶק", "devek", "glue", "клей"),
    ("נְיָר", "neyar", "paper", "папір"),
    ("דַּף", "daf", "page; sheet", "аркуш"),
    ("עַמּוּד", "amud", "page; column", "сторінка"),
    ("פֶּרֶק", "perek", "chapter", "розділ"),
    ("שִׁעוּר פְּרָטִי", "shi'ur prati", "private lesson", "приватний урок"),
    ("מַרְצֶה", "martze", "lecturer", "лектор"),
    ("הַרְצָאָה", "hartza'a", "lecture", "лекція"),
    ("תְּעוּדָה", "te'uda", "certificate", "свідоцтво"),
    ("תּוֹאַר", "to'ar", "degree; title", "ступінь"),
    ("מַחְלָקָה", "machlaka", "department", "відділ"),
]

SHOPPING_MONEY = [
    ("מְחִיר", "mechir", "price", "ціна"),
    ("עוֹלֶה", "oleh", "costs; rises", "коштує"),
    ("יָקָר", "yakar", "expensive; dear", "дорогий"),
    ("זוֹל", "zol", "cheap", "дешевий"),
    ("הַנְחָה", "hanacha", "discount", "знижка"),
    ("מִבְצָע", "mivtza", "sale; operation", "акція"),
    ("חֶשְׁבּוֹן", "cheshbon", "bill; account", "рахунок"),
    ("קַבָּלָה", "kabala", "receipt", "квитанція"),
    ("שֶׁטָר", "shetar", "banknote", "купюра"),
    ("מַטְבֵּעַ", "matbea", "coin", "монета"),
    ("עוֹדֶף", "odef", "change (money)", "решта"),
    ("אַשְׁרַאי", "ashrai", "credit", "кредит"),
    ("כַּרְטִיס אַשְׁרַאי", "kartis ashrai", "credit card", "кредитна картка"),
    ("מְזֻמָּן", "mezuman", "cash", "готівка"),
    ("חֶבְרָה", "chevra", "company; society", "компанія"),
    ("עֵסֶק", "esek", "business", "бізнес"),
    ("לָקוֹחַ", "lakoach", "customer", "клієнт"),
    ("שֵׁרוּת", "sherut", "service", "обслуговування"),
    ("מַעֲבָר", "ma'avar", "transition; crossing", "перехід"),
    ("כֶּסֶף קָטָן", "kesef katan", "small change", "дрібні гроші"),
    ("שְׁטָר חוֹב", "shtar chov", "promissory note", "вексель"),
    ("חוֹב", "chov", "debt", "борг"),
    ("הַלְוָאָה", "halva'a", "loan", "позика"),
    ("עִסְקָה", "iska", "deal; transaction", "угода"),
    ("הוֹצָאוֹת", "hotza'ot", "expenses", "витрати"),
    ("הַכְנָסָה", "hachnasa", "income", "доход"),
    ("חִסָּכוֹן", "chisachon", "savings", "заощадження"),
    ("הַשְׁקָעָה", "hashka'a", "investment", "інвестиція"),
    ("רֶוַח", "revach", "profit", "прибуток"),
    ("הֶפְסֵד", "hefsed", "loss", "збиток"),
]

TRANSPORT_TRAVEL = [
    ("רֶכֶב", "rekhev", "vehicle", "автомобіль"),
    ("אוֹטוֹבּוּס", "otobus", "bus", "автобус"),
    ("רַכֶּבֶת", "rakevet", "train", "потяг"),
    ("מוֹנִית", "monit", "taxi", "таксі"),
    ("אוֹפַנּוֹעַ", "ofnoa", "motorcycle", "мотоцикл"),
    ("אוֹפַנַּיִם", "ofanayim", "bicycle", "велосипед"),
    ("מָטוֹס", "matos", "airplane", "літак"),
    ("סְפִינָה", "sfina", "ship", "корабель"),
    ("סִירָה", "sira", "boat", "човен"),
    ("מַעְבֹּרֶת", "ma'aboret", "ferry", "пором"),
    ("מַחְסוֹם", "machsom", "barrier", "перепона"),
    ("כְּבִישׁ", "kvish", "road", "дорога"),
    ("מַסְלוּל", "maslul", "route; track", "маршрут"),
    ("רַמְזוֹר", "ramzor", "traffic light", "світлофор"),
    ("תִּמְרוּר", "timrur", "road sign", "дорожній знак"),
    ("חֲנָיָה", "chanaya", "parking", "паркування"),
    ("נְהִיגָה", "nehiga", "driving", "водіння"),
    ("רִשָּׁיוֹן", "rishayon", "license", "ліцензія"),
    ("דַּרְכּוֹן", "darkon", "passport", "паспорт"),
    ("וִיזָה", "viza", "visa", "віза"),
    ("מִזְוָדָה", "mizvada", "suitcase", "валіза"),
    ("תִּיק", "tik", "bag", "сумка"),
    ("גַּב תִּיק", "gav tik", "backpack", "рюкзак"),
    ("נְסִיעָה", "nesia", "trip; journey", "поїздка"),
    ("טִיּוּל", "tiyul", "excursion; tour", "екскурсія"),
    ("מַפָּה", "mapa", "map", "карта"),
    ("כְּתוֹבֶת", "ktovet", "address", "адреса"),
    ("מַזְכֶּרֶת", "mazkeret", "souvenir", "сувенір"),
    ("מַצְלֵמָה", "matzlema", "camera", "камера"),
    ("שִׁלְטוֹן", "shilton", "regime; authority", "влада"),
    ("דֶּגֶל", "degel", "flag", "прапор"),
    ("חוּץ לָאָרֶץ", "chutz la'aretz", "abroad", "за кордоном"),
    ("מַעֲבָר חֲצִיָּה", "ma'avar chatziya", "crosswalk", "пішохідний перехід"),
    ("מַעְפִּיל", "ma'apil", "passenger", "пасажир"),
    ("נוֹסֵעַ", "nose'a", "passenger; traveler", "пасажир"),
]

COMMUNICATION_MEDIA = [
    ("טֶלֶפוֹן", "telefon", "phone", "телефон"),
    ("נַיָּד", "nayad", "mobile", "мобільний"),
    ("הוֹדָעָה", "hoda'a", "message", "повідомлення"),
    ("שִׂיחָה", "sicha", "conversation; call", "розмова"),
    ("דֹּאַר אֶלֶקְטְרוֹנִי", "do'ar elektroni", "email", "електронна пошта"),
    ("אִינְטֶרְנֶט", "internet", "internet", "інтернет"),
    ("אֲתָר", "atar", "website; site", "сайт"),
    ("עִתּוֹן", "iton", "newspaper", "газета"),
    ("כַּתָּב", "katav", "reporter", "репортер"),
    ("חֲדָשׁוֹת", "chadashot", "news", "новини"),
    ("מַאֲמָר", "ma'amar", "article", "стаття"),
    ("פִּרְסוּם", "pirsum", "advertisement; publication", "реклама"),
    ("שִׁדּוּר", "shidur", "broadcast", "трансляція"),
    ("תָּכְנִית", "tochnit", "program; plan", "програма"),
    ("סֵרֶט", "seret", "film", "фільм"),
    ("סִדְרָה", "sidra", "series", "серіал"),
    ("שִׁיר", "shir", "song; poem", "пісня"),
    ("מוּזִיקָה", "muzika", "music", "музика"),
    ("הַקְלָטָה", "haklata", "recording", "запис"),
    ("רָאַיוֹן", "raayon", "interview", "інтерв'ю"),
    ("שְׁאֵלָה", "she'ela", "question", "питання"),
    ("תְּשׁוּבָה", "teshuva", "answer", "відповідь"),
    ("עֵדוּת", "edut", "testimony", "свідчення"),
    ("דַּעַת", "da'at", "opinion", "думка"),
    ("דַּעַת קָהָל", "da'at kahal", "public opinion", "громадська думка"),
    ("מַחֲשָׁבָה", "machshava", "thought", "думка"),
]

EMOTIONS_STATES = [
    ("אַהֲבָה", "ahava", "love", "любов"),
    ("שִׂנְאָה", "sina", "hatred", "ненависть"),
    ("שִׂמְחָה", "simcha", "joy", "радість"),
    ("עֶצֶב", "etzev", "sadness", "сум"),
    ("כַּעַס", "ka'as", "anger", "гнів"),
    ("פַּחַד", "pachad", "fear", "страх"),
    ("חֲרָדָה", "charada", "anxiety", "тривога"),
    ("דְּאָגָה", "de'aga", "worry", "турбота"),
    ("תִּקְוָה", "tikva", "hope", "надія"),
    ("אֱמוּנָה", "emuna", "faith; belief", "віра"),
    ("בִּטָּחוֹן", "bitachon", "confidence; security", "впевненість"),
    ("גַּאֲוָה", "ga'ava", "pride", "гордість"),
    ("בּוּשָׁה", "busha", "shame", "сором"),
    ("חֶרְפָּה", "cherpa", "disgrace", "ганьба"),
    ("הַפְתָּעָה", "hafta'a", "surprise", "несподіванка"),
    ("הִתְלַהֲבוּת", "hitlahavut", "enthusiasm", "захоплення"),
    ("הַרְגָּשָׁה", "hargasha", "feeling", "відчуття"),
    ("רֶגֶשׁ", "regesh", "emotion", "емоція"),
    ("מַצַּב רוּחַ", "matzav ruach", "mood", "настрій"),
    ("יְגִיעוּת", "yegi'ut", "fatigue", "втома"),
    ("מְנוּחָה", "menucha", "rest", "відпочинок"),
    ("שֵׁנָה", "shena", "sleep", "сон"),
    ("חֲלוֹם", "chalom", "dream", "сон; мрія"),
    ("רָצוֹן", "ratzon", "desire; will", "бажання"),
    ("מַטָּרָה", "matara", "goal; target", "мета"),
    ("הַצְלָחָה", "hatzlacha", "success", "успіх"),
    ("כִּשָּׁלוֹן", "kishalon", "failure", "невдача"),
    ("מַזָּל", "mazal", "luck", "удача"),
    ("בְּעָיָה", "be'aya", "problem", "проблема"),
    ("פִּתָּרוֹן", "pitaron", "solution", "розв'язання"),
    ("צַעַר", "tza'ar", "sorrow", "горе"),
    ("רַחֲמִים", "rachamim", "compassion", "співчуття"),
    ("סַבְלָנוּת", "savlanut", "patience", "терпіння"),
    ("שַׁלְוָה", "shalva", "tranquility", "спокій"),
]

ABSTRACT_COMMON = [
    ("עוֹלָם", "olam", "world", "світ"),
    ("חַיִּים", "chayim", "life", "життя"),
    ("מָוֶת", "mavet", "death", "смерть"),
    ("שָׁלוֹם", "shalom", "peace", "мир"),
    ("מִלְחָמָה", "milchama", "war", "війна"),
    ("חוֹק", "chok", "law", "закон"),
    ("זְכוּת", "zekhut", "right (entitlement)", "право"),
    ("חוֹבָה", "chova", "duty", "обов'язок"),
    ("חֵרוּת", "cherut", "freedom", "свобода"),
    ("צֶדֶק", "tzedek", "justice", "справедливість"),
    ("אֱמֶת", "emet", "truth", "правда"),
    ("שֶׁקֶר", "sheker", "lie; falsehood", "брехня"),
    ("יֹפִי", "yofi", "beauty", "краса"),
    ("כֹּחַ", "koach", "power; strength", "сила"),
    ("חֻלְשָׁה", "chulsha", "weakness", "слабкість"),
    ("דֶּרֶךְ", "derekh", "way; path", "шлях"),
    ("שִׁיטָה", "shita", "method", "метод"),
    ("מַטָּרָה", "matara", "purpose", "мета"),
    ("סִבָּה", "siba", "reason; cause", "причина"),
    ("תּוֹצָאָה", "totza'a", "result", "результат"),
    ("הֶבְדֵּל", "hevdel", "difference", "різниця"),
    ("דִּמְיוֹן", "dimyon", "imagination; similarity", "уява; схожість"),
    ("רַעְיוֹן", "ra'ayon", "idea", "ідея"),
    ("דּוּגְמָה", "dugma", "example", "приклад"),
    ("עֻבְדָּה", "uvda", "fact", "факт"),
    ("מֵידָע", "meda", "information", "інформація"),
    ("נְקֻדָּה", "nekuda", "point; period", "крапка; пункт"),
    ("שׁוּרָה", "shura", "line; row", "рядок"),
    ("טוּר", "tur", "column; row", "колонка"),
    ("צַד", "tzad", "side", "бік"),
    ("חֵלֶק", "chelek", "part", "частина"),
    ("שָׁלֵם", "shalem", "whole", "ціле"),
    ("כְּמוּת", "kamut", "quantity", "кількість"),
    ("אֵיכוּת", "eikhut", "quality", "якість"),
    ("גֹּדֶל", "godel", "size", "розмір"),
    ("מִשְׁקָל", "mishkal", "weight", "вага"),
    ("גֹּבַהּ", "govah", "height", "висота"),
    ("רֹחַב", "rochav", "width", "ширина"),
    ("אֹרֶךְ", "orekh", "length", "довжина"),
    ("עֹמֶק", "omek", "depth", "глибина"),
    ("מֶרְחָק", "merchak", "distance", "відстань"),
    ("מָקוֹם", "makom", "place", "місце"),
    ("שֵׁם", "shem", "name", "ім'я"),
    ("מִסְפָּר", "mispar", "number", "число"),
    ("סוּג", "sug", "type; kind", "тип"),
    ("מִין", "min", "kind; gender", "вид; стать"),
    ("צוּרָה", "tzura", "shape; form", "форма"),
    ("דָּבָר", "davar", "thing; matter", "річ"),
    ("עִנְיָן", "inyan", "matter; topic", "справа"),
    ("נוֹשֵׂא", "nose", "subject; topic", "тема"),
    ("מַצָּב", "matzav", "situation; state", "ситуація"),
    ("דּוּגְמָה", "dugma", "example", "приклад"),
    ("אֶפְשָׁרוּת", "efsharut", "possibility", "можливість"),
    ("מַחְלוֹקֶת", "machloket", "dispute", "суперечка"),
    ("חֲשִׁיבוּת", "chashivut", "importance", "важливість"),
    ("הֶמְשֵׁךְ", "hemshekh", "continuation", "продовження"),
    ("שִׁנּוּי", "shinui", "change", "зміна"),
    ("פִּתּוּחַ", "pituach", "development", "розвиток"),
    ("הִתְקַדְּמוּת", "hitkadmut", "progress", "прогрес"),
]

CATEGORIES = [
    ("function_words", FUNCTION_WORDS),
    ("pronouns_demonstratives", PRONOUNS),
    ("questions_quantifiers", QUESTIONS_QUANTIFIERS),
    ("verbs", VERBS),
    ("adjectives", ADJECTIVES),
    ("colors", COLORS),
    ("time", TIME),
    ("family", FAMILY),
    ("body_health", BODY_HEALTH),
    ("food", FOOD),
    ("clothing", CLOTHING),
    ("home", HOME),
    ("city_places", CITY_PLACES),
    ("nature_weather", NATURE_WEATHER),
    ("animals", ANIMALS),
    ("work", WORK),
    ("education", EDUCATION),
    ("shopping_money", SHOPPING_MONEY),
    ("transport_travel", TRANSPORT_TRAVEL),
    ("communication_media", COMMUNICATION_MEDIA),
    ("emotions_states", EMOTIONS_STATES),
    ("abstract_common", ABSTRACT_COMMON),
]


def main() -> None:
    out = []
    for cat, items in CATEGORIES:
        for hebrew, transcription, english, ukrainian in items:
            out.append({
                "hebrew": hebrew,
                "transcription": transcription,
                "english": english,
                "ukrainian": ukrainian,
                "category": cat,
            })
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {len(out)} candidate entries to {OUT}")


if __name__ == "__main__":
    main()
