from typing import Protocol


class ContentRepositoryPort(Protocol):
    def load_words(self): ...

    def load_guide_sections(self): ...

    def load_verbs(self): ...

    def load_reading_sections(self): ...


class ProgressRepositoryPort(Protocol):
    def save_words(self, words): ...
